[package]
name = "nostd_cow"
version = "0.1.0"
edition = "2021"

[dependencies]

[features]
alloc = []
std = ["alloc"]

[package.metadata.docs.rs]
all-features = true

rustdoc-args = ["--cfg", "docsrs"]